exports.fonts = [
  "Acme, sans-serif",
  "Alegreya Sans, sans-serif",
  "Alegreya, serif",
  "Anton, sans-serif",
  "Anton, sans-serif",
  "Archivo Black, sans-serif",
  "Archivo Narrow, sans-serif",
  "Archivo, sans-serif",
  "Arimo, sans-serif",
  "Arvo, serif",
  "Asap Condensed, sans-serif",
  "Bitter, serif",
  "Bowlby One SC, cursive",
  "Cabin, sans-serif",
  "Crete Round, serif",
  "Cuprum, sans-serif",
  "Dosis, sans-serif",
  "Droid Sans, sans-serif",
  "EB Garamond, serif",
  "Exo, sans-serif",
  "Faustina, serif",
  "Fjalla One, sans-serif",
  "Francois One, sans-serif",
  "Hind, sans-serif",
  "Inconsolata, monospace",
  "Indie Flower, cursive",
  "Josefin Sans, sans-serif",
  "Julee, cursive",
  "Lato, sans-serif",
  "Libre Franklin, sans-serif",
  "Lora, serif",
  "Mada, sans-serif",
  "Manuale, serif",
  "Maven Pro, sans-serif",
  "Merriweather, serif",
  "Montserrat, sans-serif",
  "Mukta Vaani, sans-serif",
  "Muli, sans-serif",
  "Noto Sans, sans-serif",
  "Noto Serif, serif",
  "Open Sans Condensed, sans-serif",
  "Open Sans, sans-serif",
  "Oswald, sans-serif",
  "Oxygen, sans-serif",
  "PT Sans Caption, sans-serif",
  "PT Sans Narrow, sans-serif",
  "PT Sans, sans-serif",
  "PT Serif, serif",
  "Passion One, cursive",
  "Pathway Gothic One, sans-serif",
  "Play, sans-serif",
  "Playfair Display, serif",
  "Poppins, sans-serif",
  "Raleway, sans-serif",
  "Roboto Condensed, sans-serif",
  "Roboto Slab, serif",
  "Ropa Sans, sans-serif",
  "Saira Condensed, sans-serif",
  "Saira, sans-serif",
  "Sedgwick Ave Display, cursive",
  "Slabo 27px, serif",
  "Source Sans Pro, sans-serif",
  "Spectral, serif",
  "Titillium Web, sans-serif",
  "Ubuntu, sans-serif",
  "Vollkorn, serif",
  "Zilla Slab Highlight, cursive",
  "Zilla Slab, serif",
];
